FROM ubuntu:24.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
      openssh-server sudo tini build-essential python3 python3-pip python3-venv \
      nodejs npm git curl wget vim tmux htop man-db ca-certificates locales \
      && rm -rf /var/lib/apt/lists/*
RUN locale-gen en_US.UTF-8
# cloud user with passwordless sudo
RUN useradd -m -u 1001 -s /bin/bash -G sudo cloud \
    && echo 'cloud ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/cloud \
    && chmod 0440 /etc/sudoers.d/cloud
RUN mkdir -p /run/sshd && ssh-keygen -A
RUN sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config \
    && sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config \
    && sed -i 's/^#\?AllowTcpForwarding.*/AllowTcpForwarding yes/' /etc/ssh/sshd_config \
    && sed -i 's/^#\?X11Forwarding.*/X11Forwarding yes/' /etc/ssh/sshd_config
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENV LANG=en_US.UTF-8
EXPOSE 22 8080
ENTRYPOINT ["/usr/bin/tini", "--", "/entrypoint.sh"]
